// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingMicroservice.ProductAPI.Model.Context;

#nullable disable

namespace ShoppingMicroservice.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20240203013344_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShoppingMicroservice.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "CAMISETA",
                            Description = "A camiseta Nike Sportswear coloca você em um macio tecido jersey de algodão e um logotipo clássico no peito.",
                            ImageURL = "https://imgnike-a.akamaihd.net/768x768/01638851.jpg",
                            Name = "Camiseta Nike Sportswear Icon Futura Masculina",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "CAMISETA",
                            Description = "A Coleção da Seleção Brasileira de 2022 combina a icônica estampa da onça-pintada com design inovador que mantém seu corpo seco mesmo no auge da empolgação.",
                            ImageURL = "https://imgnike-a.akamaihd.net/768x768/0226290L.jpg",
                            Name = "Camisa Nike Brasil I 2022/23 Jogador Masculina",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "TENIS",
                            Description = "O Invincible Run 3 possui amortecimento espesso para ajudar você a ficar atento e ativo hoje, amanhã e sempre.",
                            ImageURL = "https://imgnike-a.akamaihd.net/768x768/02523151.jpg",
                            Name = "Tênis Nike Invincible 3 Masculino",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "MOCHILA",
                            Description = "Carregue seu equipamento com a mochila Nike Heritage.",
                            ImageURL = "https://imgnike-a.akamaihd.net/768x768/012822O6A1.jpg",
                            Name = "Mochila Nike Heritage Unissex\r\n",
                            Price = 279.99m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "BLUSA",
                            Description = "Comece e termine sua aventura ao ar livre com este moletom confortável para corrida em trilha.",
                            ImageURL = "https://imgnike-a.akamaihd.net/768x768/024982NX.jpg",
                            Name = "Blusão Nike Dri-FIT Magic Hour Masculino\r\n",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "TENIS",
                            Description = "Camadas sobre camadas de estilo e conforto - essa é uma força a ser reconhecida.",
                            ImageURL = "https://imgnike-a.akamaihd.net/768x768/02567551.jpg",
                            Name = "Tênis Nike Gamma Force Feminino\r\n",
                            Price = 699.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
